import {
  HIDE_INVESTIGATIONS_VIEW_RESULT_MODAL,
  REMOVE_INVESTIGATIONS_VIEW_RESULT_ATTACHMENT,
  RESET_INVESTIGATIONS_VIEW_REQUEST,
  RESET_INVESTIGATIONS_VIEW_RESULT,
  SHOW_INVESTIGATIONS_VIEW_RESULT_MODAL,
  UPDATE_INVESTIGATIONS_REQUESTS,
  UPDATE_INVESTIGATIONS_RESULTS,
  UPDATE_INVESTIGATIONS_VIEW_REQUEST,
  UPDATE_INVESTIGATIONS_VIEW_RESULT_ATTACHMENTS,
  UPDATE_INVESTIGATIONS_VIEW_RESULT_DESCRIPTION,
  UPDATE_INVESTIGATIONS_VIEW_RESULT_NOTES,
} from '../constants';

describe('InvestigationEntry action constants', () => {
  it('HIDE_INVESTIGATIONS_VIEW_RESULT_MODAL', () => {
    expect(HIDE_INVESTIGATIONS_VIEW_RESULT_MODAL).toMatchSnapshot();
  });
  it('REMOVE_INVESTIGATIONS_VIEW_RESULT_ATTACHMENT', () => {
    expect(REMOVE_INVESTIGATIONS_VIEW_RESULT_ATTACHMENT).toMatchSnapshot();
  });
  it('RESET_INVESTIGATIONS_VIEW_REQUEST', () => {
    expect(RESET_INVESTIGATIONS_VIEW_REQUEST).toMatchSnapshot();
  });
  it('RESET_INVESTIGATIONS_VIEW_RESULT', () => {
    expect(RESET_INVESTIGATIONS_VIEW_RESULT).toMatchSnapshot();
  });
  it('SHOW_INVESTIGATIONS_VIEW_RESULT_MODAL', () => {
    expect(SHOW_INVESTIGATIONS_VIEW_RESULT_MODAL).toMatchSnapshot();
  });
  it('UPDATE_INVESTIGATIONS_REQUESTS', () => {
    expect(UPDATE_INVESTIGATIONS_REQUESTS).toMatchSnapshot();
  });
  it('UPDATE_INVESTIGATIONS_RESULTS', () => {
    expect(UPDATE_INVESTIGATIONS_RESULTS).toMatchSnapshot();
  });
  it('UPDATE_INVESTIGATIONS_VIEW_REQUEST', () => {
    expect(UPDATE_INVESTIGATIONS_VIEW_REQUEST).toMatchSnapshot();
  });
  it('UPDATE_INVESTIGATIONS_VIEW_RESULT_ATTACHMENTS', () => {
    expect(UPDATE_INVESTIGATIONS_VIEW_RESULT_ATTACHMENTS).toMatchSnapshot();
  });
  it('UPDATE_INVESTIGATIONS_VIEW_RESULT_DESCRIPTION', () => {
    expect(UPDATE_INVESTIGATIONS_VIEW_RESULT_DESCRIPTION).toMatchSnapshot();
  });
  it('UPDATE_INVESTIGATIONS_VIEW_RESULT_NOTES', () => {
    expect(UPDATE_INVESTIGATIONS_VIEW_RESULT_NOTES).toMatchSnapshot();
  });
});
