import {
  REPLACE_PATIENT_MEDICAL_RECORD_NUMBER,
  REPLACE_PATIENT_NAME,
  UPDATE_PATIENT_AGE,
  UPDATE_PATIENT_AGE_GROUP,
  UPDATE_PATIENT_ANIMAL_TYPE,
  UPDATE_PATIENT_CATEGORY,
  UPDATE_PATIENT_CIRCUMSTANCE,
  UPDATE_PATIENT_LOCATION,
  UPDATE_PATIENT_MEDICAL_RECORD_NUMBER,
  UPDATE_PATIENT_NAME,
  UPDATE_PATIENT_OCCUPATION,
  UPDATE_PATIENT_POISON_SEVERITY_SCORE,
  UPDATE_PATIENT_SUBURB,
  UPDATE_PATIENT_POSTCODE,
  UPDATE_PATIENT_GEOMETRY,
  UPDATE_PATIENT_PREGNANT_LACTATING,
  UPDATE_PATIENT_PREGNANT_STATUS,
  UPDATE_PATIENT_PREGNANT_TRIMESTER,
  UPDATE_PATIENT_PREGNANT_TRIMESTER_UNKNOWN,
  UPDATE_PATIENT_RISK_ASSESSMENT,
  UPDATE_PATIENT_SEX,
  UPDATE_PATIENT_WEIGHT,
} from '../constants';

describe('Patient action constants', () => {
  it('REPLACE_PATIENT_MEDICAL_RECORD_NUMBER', () => {
    expect(REPLACE_PATIENT_MEDICAL_RECORD_NUMBER).toMatchSnapshot();
  });
  it('REPLACE_PATIENT_NAME', () => {
    expect(REPLACE_PATIENT_NAME).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_AGE', () => {
    expect(UPDATE_PATIENT_AGE).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_AGE_GROUP', () => {
    expect(UPDATE_PATIENT_AGE_GROUP).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_ANIMAL_TYPE', () => {
    expect(UPDATE_PATIENT_ANIMAL_TYPE).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_CATEGORY', () => {
    expect(UPDATE_PATIENT_CATEGORY).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_CIRCUMSTANCE', () => {
    expect(UPDATE_PATIENT_CIRCUMSTANCE).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_LOCATION', () => {
    expect(UPDATE_PATIENT_LOCATION).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_MEDICAL_RECORD_NUMBER', () => {
    expect(UPDATE_PATIENT_MEDICAL_RECORD_NUMBER).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_NAME', () => {
    expect(UPDATE_PATIENT_NAME).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_OCCUPATION', () => {
    expect(UPDATE_PATIENT_OCCUPATION).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_POISON_SEVERITY_SCORE', () => {
    expect(UPDATE_PATIENT_POISON_SEVERITY_SCORE).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_SUBURB', () => {
    expect(UPDATE_PATIENT_SUBURB).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_POSTCODE', () => {
    expect(UPDATE_PATIENT_POSTCODE).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_GEOMETRY', () => {
    expect(UPDATE_PATIENT_GEOMETRY).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_PREGNANT_LACTATING', () => {
    expect(UPDATE_PATIENT_PREGNANT_LACTATING).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_PREGNANT_STATUS', () => {
    expect(UPDATE_PATIENT_PREGNANT_STATUS).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_PREGNANT_TRIMESTER', () => {
    expect(UPDATE_PATIENT_PREGNANT_TRIMESTER).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_PREGNANT_TRIMESTER_UNKNOWN', () => {
    expect(UPDATE_PATIENT_PREGNANT_TRIMESTER_UNKNOWN).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_RISK_ASSESSMENT', () => {
    expect(UPDATE_PATIENT_RISK_ASSESSMENT).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_SEX', () => {
    expect(UPDATE_PATIENT_SEX).toMatchSnapshot();
  });
  it('UPDATE_PATIENT_WEIGHT', () => {
    expect(UPDATE_PATIENT_WEIGHT).toMatchSnapshot();
  });
});
