export const TOGGLE_NEW_CALL_MODAL = 'pic/ActionBarContainer/TOGGLE_NEW_CALL_MODAL';
export const UPDATE_NEW_CALL_MODAL_CALLER_LOCATION = 'pic/ActionBarContainer/UPDATE_NEW_CALL_MODAL_CALLER_LOCATION';
export const UPDATE_NEW_CALL_MODAL_CALLER_ORGANISATION = 'pic/ActionBarContainer/UPDATE_NEW_CALL_MODAL_CALLER_ORGANISATION';
export const UPDATE_NEW_CALL_MODAL_CENTRE_NAME = 'pic/ActionBarContainer/UPDATE_NEW_CALL_MODAL_CENTRE_NAME';
export const UPDATE_NEW_CALL_MODAL_FILTER = 'pic/ActionBarContainer/UPDATE_NEW_CALL_MODAL_FILTER';
export const UPDATE_NEW_CALL_MODAL_ID = 'pic/ActionBarContainer/UPDATE_NEW_CALL_MODAL_ID';
export const UPDATE_NEW_CALL_MODAL_NAME = 'pic/ActionBarContainer/UPDATE_NEW_CALL_MODAL_NAME';
export const UPDATE_NEW_CALL_MODAL_SELECTED = 'pic/ActionBarContainer/UPDATE_NEW_CALL_MODAL_SELECTED';
export const UPDATE_NEW_CALL_MODAL_SEX = 'pic/ActionBarContainer/UPDATE_NEW_CALL_MODAL_SEX';
export const UPDATE_NEW_CALL_MODAL_POSTCODE = 'pic/ActionBarContainer/UPDATE_NEW_CALL_MODAL_POSTCODE';
export const UPDATE_NEW_CALL_MODAL_TIME = 'pic/ActionBarContainer/UPDATE_NEW_CALL_MODAL_TIME';

