import {
  UPDATE_CASE_LIST_SEARCH_CALLER_LOCATION,
  UPDATE_CASE_LIST_SEARCH_CALLER_ORGANISATION,
  UPDATE_CASE_LIST_SEARCH_CENTRE_NAME,
  UPDATE_CASE_LIST_SEARCH_FILTER,
  UPDATE_CASE_LIST_SEARCH_ID,
  UPDATE_CASE_LIST_SEARCH_NAME,
  UPDATE_CASE_LIST_SEARCH_POSTCODE,
  UPDATE_CASE_LIST_SEARCH_SEX,
  UPDATE_CASE_LIST_SEARCH_TIME,
} from '../constants';

describe('Patient action constants', () => {
  it('UPDATE_CASE_LIST_SEARCH_CALLER_LOCATION', () => {
    expect(UPDATE_CASE_LIST_SEARCH_CALLER_LOCATION).toMatchSnapshot();
  });
  it('UPDATE_CASE_LIST_SEARCH_CALLER_ORGANISATION', () => {
    expect(UPDATE_CASE_LIST_SEARCH_CALLER_ORGANISATION).toMatchSnapshot();
  });
  it('UPDATE_CASE_LIST_SEARCH_CENTRE_NAME', () => {
    expect(UPDATE_CASE_LIST_SEARCH_CENTRE_NAME).toMatchSnapshot();
  });
  it('UPDATE_CASE_LIST_SEARCH_FILTER', () => {
    expect(UPDATE_CASE_LIST_SEARCH_FILTER).toMatchSnapshot();
  });
  it('UPDATE_CASE_LIST_SEARCH_ID', () => {
    expect(UPDATE_CASE_LIST_SEARCH_ID).toMatchSnapshot();
  });
  it('UPDATE_CASE_LIST_SEARCH_NAME', () => {
    expect(UPDATE_CASE_LIST_SEARCH_NAME).toMatchSnapshot();
  });
  it('UPDATE_CASE_LIST_SEARCH_POSTCODE', () => {
    expect(UPDATE_CASE_LIST_SEARCH_POSTCODE).toMatchSnapshot();
  });
  it('UPDATE_CASE_LIST_SEARCH_SEX', () => {
    expect(UPDATE_CASE_LIST_SEARCH_SEX).toMatchSnapshot();
  });
  it('UPDATE_CASE_LIST_SEARCH_TIME', () => {
    expect(UPDATE_CASE_LIST_SEARCH_TIME).toMatchSnapshot();
  });
});
